name: ABI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-abis:
    name: Generate ABIs
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Setup environment
        run: |
          yarn install
          cp .env.example.json .env.json
          yarn compile
          npm install -g fx

      - name: Copy UI ABIs
        run: |
        cp artifacts/contracts/StakedBNBToken.sol/StakedBNBToken.json abis/ui/

      - name: Extract info for Go ABIs
        run: |
          mkdir temp
          fx artifacts/contracts/StakedBNBToken.sol/StakedBNBToken.json .abi > temp/StakedBNBToken.json
          fx artifacts/contracts/StakedBNBToken.sol/StakedBNBToken.json .bytecode > temp/StakedBNBToken.bin

      - name: Generate Go ABIs
        run: |
        chmod 755 .github/workflows/abigen
        ./.github/workflows/abigen --abi=temp/StakedBNBToken.json --bin=temp/StakedBNBToken.bin --pkg=contracts --type=StakedBNBToken --out=abis/go/staked_bnb_token.go
        rm -rf temp

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'CI: Generated ABIs'
          add: 'abis/*'  