name: Certora

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

  workflow_dispatch:

jobs:
  get-diff:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.certora.outputs.run }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        id: git-diff # via outputs
        with:
          PATTERNS: |
            +(contracts)/*.sol
            +(contracts|certora)/**/*.sol

      - id: certora
        run: echo "::set-output name=run::true"
        if: steps.git-diff.outputs.diff

  verify_stkBNB:
    runs-on: ubuntu-latest
    if: needs.get-diff.outputs.output1 == 'true'
    needs: get-diff

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: yarn install

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.7/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc          
          pip3 install certora-cli==3.3.2

      - name: Prepare
        run: |
          chmod +x certora/scripts/*.sh

      - name: Verify with Certora
        run: |
          certora/scripts/ci.sh
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        