name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  # add get-diff job
  get-diff:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      contract: ${{ steps.get-diff-contract.outputs.diff }}
      certora-contract: ${{ steps.get-diff-certora-contract.outputs.diff }}
      certora-spec: ${{ steps.get-diff-certora-spec.outputs.diff }}
      scripts: ${{ steps.get-diff-scripts.outputs.diff }}
      agents: ${{ steps.get-diff-agents.outputs.diff }}
      env: ${{ steps.get-diff-env.outputs.diff }}

    steps:
      - uses: actions/checkout@v3

      - name: Get diff for contract
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-contract # via outputs
        with:
          PATTERNS: |
            +(contracts)/*.sol
            +(contracts/**/*.sol

      - name: Get diff for certora contract
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-certora-contract # via outputs
        with:
          PATTERNS: |
            +(certora)/**/*.sol

      - name: Get diff for certora specs/scripts
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-certora-spec # via outputs
        with:
          PATTERNS: |
            +(certora)/**/*.spec
            +(certora)/**/ci.sh

      - name: Get diff for scripts/test
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-scripts # via outputs
        with:
          PATTERNS: |
            +(scripts|test)/*.+(js|ts)
            +(scripts|test)/**/*.+(js|ts)
            +hardhat.config.ts
            +.eslintrc.js

      - name: Get diff for agents
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-agents # via outputs
        with:
          PATTERNS: |
            +(agents)/*.+(js|ts)
            +(agents)/**/*.+(js|ts)
            +.eslintrc.js

      - name: Get diff for example env
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-env # via outputs
        with:
          PATTERNS: |
            +.env.example.json

  contract-size:
    name: Contract Size
    runs-on: ubuntu-latest
    needs: generate-json-schema
    if: ${{ always() && !contains(join(needs.generate-json-schema.result, ','), 'failure')  && needs.get-diff.outputs.contract }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Setup Environment
        run: |
          yarn install
          cp .env.example.json .env.json

      - name: Run Contract-sizer
        run: |
          yarn contract:size

  test-contract:
    name: Test Contract
    runs-on: ubuntu-latest
    needs: generate-json-schema
    if: ${{ always() && !contains(join(needs.generate-json-schema.result, ','), 'failure') && (needs.get-diff.outputs.contract || needs.get-diff.outputs.scripts)}}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Setup Environment
        run: |
          yarn install
          cp .env.example.json .env.json

      - name: Run test and coverage
        run: |
          yarn test:coverage

  linter:
    name: Linter check
    runs-on: ubuntu-latest
    needs: generate-json-schema
    if: ${{ always() && !contains(join(needs.generate-json-schema.result, ','), 'failure') && (needs.get-diff.outputs.contract || needs.get-diff.outputs.certora-contract || needs.get-diff.outputs.scripts || needs.get-diff.outputs.agents)}}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Setup Environment
        run: |
          yarn install

      - name: Run Linter check
        run: |
          yarn lint:check

  solhint:
    name: Solhint
    runs-on: ubuntu-latest
    needs: linter
    if: needs.get-diff.outputs.contract

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16

      - name: Setup Environment
        run: |
          yarn install

      - name: Run Solhint
        run: |
          yarn solhint   

  certora:
    runs-on: ubuntu-latest
    if: needs.get-diff.outputs.certora-contract || needs.get-diff.outputs.contract || needs.get-diff.outputs.certora-spec
    needs: get-diff

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: yarn install

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.7/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc          
          pip3 install certora-cli

      - name: Prepare
        run: |
          chmod +x certora/scripts/*.sh

      - name: Verify with Certora
        run: |
          certora/scripts/ci.sh
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

  slither-analyze:
    name: Slither Analysis
    runs-on: ubuntu-latest
    needs: get-diff
    permissions:
      contents: read
      actions: read
      security-events: write
    if: needs.get-diff.outputs.contract

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          yarn install
          cp .env.example.json .env.json

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          node-version: 16
          sarif: results.sarif

    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: "${{ steps.slither.outputs.sarif }}"