name: Slither Analysis

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main
      - release/**

jobs:
  get-diff:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output-contract: ${{ steps.contract.outputs.run }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Get diff for contract
        uses: technote-space/get-diff-action@v4.0.1
        id: get-diff-contract # via outputs
        with:
          PATTERNS: |
            +(contracts)/*.sol

      - id: contract
        run: echo "::set-output name=run::true"
        if: steps.get-diff-contract.outputs.diff
  
  slither-analyze:
    name: Slither Analysis
    runs-on: ubuntu-latest
    needs: get-diff
    permissions:
      contents: read
      actions: read
      security-events: write
    if: needs.get-diff.outputs.output-contract == 'true'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          yarn install
          cp .env.example.json .env.json

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          node-version: 16
          sarif: results.sarif

    # - name: Upload SARIF file
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: "${{ steps.slither.outputs.sarif }}"